version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.3.2
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - wetraveltogether
      - wetraveltogether-mysql

  grafana:
    image: grafana/grafana:5.2.2
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./grafana.env

  wetraveltogether-mysql:
    container_name: weTravelTogether-mysql
    image: mysql/mysql-server:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: wetraveltogether
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always

  mysqlexporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      - "DATA_SOURCE_NAME=root:12345678@(wetraveltogether-mysql:3306)/"

  wetraveltogether:
    restart: always
    build: ./
    working_dir: /weTravelTogether
    volumes:
      - ./weTravelTogether:/weTravelTogether
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - wetraveltogether-mysql
    container_name: spring

