version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.3.2
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:5.2.2
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./grafana.env
  weTravelTogether-nginx:
    container_name: weTravelTogether-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  weTravelTogether-mysql:
    container_name: weTravelTogether-mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: wetraveltogether
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    restart: always
    build: ./wetraveltogether
    working_dir: /wetraveltogether
    volumes:
      - ./wetraveltogether:/wetraveltogether
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - hk-mysql
