global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring:8080']
  - job_name: 'wetraveltogether-mysql'
    static_configs:
      - targets: ['weTravelTogether-mysql:3306']

